blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULL_PARAM = {'null': True, 'blank': True}


class Blog(models.Model):

    title = models.CharField(max_length=50, verbose_name='заголовок')
    slug = models.CharField(max_length=50, verbose_name='URL')
    email = models.CharField(max_length=150, verbose_name='Почта', unique=True, **NULL_PARAM)
    content = models.TextField(verbose_name='содержимое', **NULL_PARAM)
    preview = models.ImageField(upload_to='blog/', verbose_name='превью', **NULL_PARAM)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    publication = models.BooleanField(default=True, verbose_name='факт публикации')
    views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f' {self.title} - {self.slug}, views: {self.views}, date: {self.date_created}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/forms.py
from django import forms

from blog.models import Blog


class BlogForm(forms.ModelForm):

    class Meta:
        model = Blog
        # fields = '__all__'
        fields = ('title', 'content', 'preview', 'email',)

    def clean_email(self):
        cleaned_data = self.cleaned_data['email']
        if 'sky.pro' in cleaned_data:
            raise forms.ValidationError('Почта должна заканчиваться на sky.pro')
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from blog.forms import BlogForm


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    # fields = ('title', 'content', 'preview')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_dealer = form.save()
            new_dealer.slug = slugify(new_dealer.title)
            new_dealer.save()
        return super().form_valid(form)


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication=True)
        return queryset


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_dealer = form.save()
            new_dealer.slug = slugify(new_dealer.title)
            new_dealer.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mystore</h1>
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Удаление</h4>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-lg btn-outline-danger">
                                Удалить {{object.title }} ?
                            </button>
                            <a type="submit" class="btn btn-lg btn-outline-primary"
                               href="{% url 'blog:list' %}">Отмена
                            </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h1 class="card-title">{{ object.title }}</h1>
                    <img class="card-img-top" src="{{ object.preview }}">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.slug }}</li>
                        <li>- {{ object.content }}</li>
                        <li>- {{ object.preview }}</li>
                        <li>- {{ object.date_created }}</li>
                    </ul>
                    <div class="btn-group">
                        <a href="{% url 'blog:edit' object.pk %}"
                           class="btn btn-lg btn-block btn-outline-primary">Править</a>
                        <a href="{% url 'blog:delete' object.pk %}"
                           class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
                    </div>
                    <div class="card-footer">
                        Посещений: {{ object.views }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html'%}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Отправить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">{{ object.title }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blog:view' object.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                            <a href="{% url 'blog:edit' object.pk %}" class="btn btn-sm btn-outline-secondary">Edit</a>
                            <a href="{% url 'blog:delete' object.pk %}" class="btn btn-sm btn-outline-danger">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}